// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright © 2021-2026 Adrian <adrian.eddy at gmail>
//
// Normalized camera / lens catalog for selector UIs (gyroflow/gyroflow#742).
// The JSON is independent of individual lens-profile files: those strings
// should converge onto the names stored here.

use std::collections::{ HashMap, HashSet };
use std::path::PathBuf;

use serde::{ Deserialize, Serialize };

use crate::lens_profile::LensProfile;
use crate::lens_profile_database::LensProfileDatabase;

/// Bundled catalog generated by `_scripts/generate_camera_database.py`.
const BUNDLED_CAMERA_DATABASE: &str = include_str!("../../resources/camera_database.json");

/// ComboBox sentinel for free-typed values that are not in the catalog.
pub const OTHER: &str = "Other";

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Brand {
    pub id: String,
    pub name: String,
    pub aliases: Vec<String>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Mount {
    pub id: String,
    pub name: String,
    pub aliases: Vec<String>,
    pub compat: Vec<String>,
    pub flange_focal_distance_mm: Option<f64>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct SensorSize {
    pub id: String,
    pub name: String,
    pub width_mm: Option<f64>,
    pub height_mm: Option<f64>,
    pub crop_factor: f64,
    pub aliases: Vec<String>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Camera {
    pub id: String,
    pub brand_id: String,
    pub name: String,
    pub aliases: Vec<String>,
    pub mount_id: Option<String>,
    pub sensor_size_id: Option<String>,
    pub crop_factor: Option<f64>,
    pub fixed_lens: bool,
    pub sources: Vec<String>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct Lens {
    pub id: String,
    pub brand_id: String,
    pub name: String,
    pub aliases: Vec<String>,
    pub mount_id: Option<String>,
    pub camera_ids: Vec<String>,
    pub focal_min_mm: Option<f64>,
    pub focal_max_mm: Option<f64>,
    pub aperture_min: Option<f64>,
    pub kind: String,
    pub sources: Vec<String>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct CameraDatabase {
    pub version: u32,
    pub generated_at: String,
    pub sources: serde_json::Value,
    pub brands: Vec<Brand>,
    pub mounts: Vec<Mount>,
    pub sensor_sizes: Vec<SensorSize>,
    pub cameras: Vec<Camera>,
    pub lenses: Vec<Lens>,

    #[serde(skip)]
    brand_by_alias: HashMap<String, usize>,
    #[serde(skip)]
    brand_by_id: HashMap<String, usize>,
    #[serde(skip)]
    camera_by_id: HashMap<String, usize>,
    #[serde(skip)]
    camera_by_match: HashMap<String, usize>,
    #[serde(skip)]
    lens_by_id: HashMap<String, usize>,
    #[serde(skip)]
    mount_by_id: HashMap<String, usize>,
    #[serde(skip)]
    sensor_by_id: HashMap<String, usize>,
}

#[derive(Clone, Debug, Default, Serialize)]
pub struct ResolvedSelection {
    pub brand: String,
    pub model: String,
    pub lens: String,
    pub brand_id: Option<String>,
    pub camera_id: Option<String>,
    pub lens_id: Option<String>,
    pub mount: Option<String>,
    pub sensor_size: Option<String>,
    pub crop_factor: Option<f64>,
    pub fixed_lens: bool,
    pub used_other: bool,
}

#[derive(Clone, Debug, Default, Serialize)]
pub struct CompatibleCamera {
    pub brand: String,
    pub model: String,
    pub mount: Option<String>,
    pub sensor_size: Option<String>,
    pub crop_factor: Option<f64>,
}

impl CameraDatabase {
    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        let mut db: Self = serde_json::from_str(json)?;
        db.rebuild_indexes();
        Ok(db)
    }

    pub fn bundled() -> Self {
        Self::from_json(BUNDLED_CAMERA_DATABASE).unwrap_or_else(|e| {
            log::error!("Failed to parse bundled camera_database.json: {e:?}");
            Self::default()
        })
    }

    /// Load an updated catalog from disk when present, otherwise the bundled copy.
    pub fn load_default() -> Self {
        for path in Self::search_paths() {
            if path.exists() {
                match std::fs::read_to_string(&path) {
                    Ok(json) => match Self::from_json(&json) {
                        Ok(db) => {
                            log::info!("Loaded camera database from {} ({} cameras, {} lenses)", path.display(), db.cameras.len(), db.lenses.len());
                            return db;
                        }
                        Err(e) => log::warn!("Failed to parse camera database {}: {e:?}", path.display()),
                    },
                    Err(e) => log::warn!("Failed to read camera database {}: {e:?}", path.display()),
                }
            }
        }
        let db = Self::bundled();
        log::info!("Using bundled camera database ({} cameras, {} lenses)", db.cameras.len(), db.lenses.len());
        db
    }

    pub fn search_paths() -> Vec<PathBuf> {
        let mut paths = Vec::new();
        paths.push(crate::settings::data_dir().join("lens_profiles").join("camera_database.json"));
        paths.push(LensProfileDatabase::get_path().join("camera_database.json"));
        if let Ok(manifest) = std::env::var("CARGO_MANIFEST_DIR") {
            paths.push(PathBuf::from(manifest).join("../../resources/camera_database.json"));
        }
        paths
    }

    pub fn filename() -> &'static str { "camera_database.json" }

    fn rebuild_indexes(&mut self) {
        self.brand_by_alias.clear();
        self.brand_by_id.clear();
        self.camera_by_id.clear();
        self.camera_by_match.clear();
        self.lens_by_id.clear();
        self.mount_by_id.clear();
        self.sensor_by_id.clear();

        for (i, b) in self.brands.iter().enumerate() {
            self.brand_by_id.insert(b.id.clone(), i);
            self.brand_by_alias.insert(brand_lookup_key(&b.name), i);
            for a in &b.aliases {
                self.brand_by_alias.entry(brand_lookup_key(a)).or_insert(i);
            }
        }
        for (i, m) in self.mounts.iter().enumerate() {
            self.mount_by_id.insert(m.id.clone(), i);
        }
        for (i, s) in self.sensor_sizes.iter().enumerate() {
            self.sensor_by_id.insert(s.id.clone(), i);
        }
        for (i, c) in self.cameras.iter().enumerate() {
            self.camera_by_id.insert(c.id.clone(), i);
            self.camera_by_match.insert(camera_match_key(&c.brand_id, &c.name), i);
            for a in &c.aliases {
                self.camera_by_match.entry(camera_match_key(&c.brand_id, a)).or_insert(i);
            }
        }
        for (i, l) in self.lenses.iter().enumerate() {
            self.lens_by_id.insert(l.id.clone(), i);
        }
    }

    pub fn brand_names(&self) -> Vec<String> {
        let mut names: Vec<String> = self.brands.iter().map(|b| b.name.clone()).collect();
        names.sort_by(|a, b| a.to_ascii_lowercase().cmp(&b.to_ascii_lowercase()));
        names
    }

    pub fn model_names(&self, brand: &str) -> Vec<String> {
        if is_other(brand) { return Vec::new(); }
        let Some(b) = self.resolve_brand(brand) else { return Vec::new(); };
        let mut names: Vec<String> = self.cameras.iter()
            .filter(|c| c.brand_id == b.id)
            .map(|c| c.name.clone())
            .collect();
        names.sort_by(|a, b| a.to_ascii_lowercase().cmp(&b.to_ascii_lowercase()));
        names.dedup();
        names
    }

    pub fn lens_names(&self, brand: &str, model: &str) -> Vec<String> {
        if is_other(brand) || is_other(model) { return Vec::new(); }
        let Some(cam) = self.resolve_camera(brand, model) else {
            // Still offer brand-level lenses (LensFun third-party glass after brand-only pick).
            return self.lenses_for_brand(brand);
        };
        let mut names: Vec<String> = Vec::new();
        let mut seen = HashSet::new();

        let push = |names: &mut Vec<String>, seen: &mut HashSet<String>, name: &str| {
            if seen.insert(name.to_ascii_lowercase()) {
                names.push(name.to_string());
            }
        };

        for lens in &self.lenses {
            if lens.camera_ids.iter().any(|id| id == &cam.id) {
                push(&mut names, &mut seen, &lens.name);
            }
        }
        if !cam.fixed_lens {
            if let Some(mount) = cam.mount_id.as_deref() {
                for lens in &self.lenses {
                    if lens.mount_id.as_deref() == Some(mount) {
                        push(&mut names, &mut seen, &lens.name);
                    }
                }
            }
        }
        if names.is_empty() {
            for lens in &self.lenses {
                if lens.brand_id == cam.brand_id {
                    push(&mut names, &mut seen, &lens.name);
                }
            }
        }
        names.sort_by(|a, b| a.to_ascii_lowercase().cmp(&b.to_ascii_lowercase()));
        const CAP: usize = 250;
        if names.len() > CAP {
            names.truncate(CAP);
        }
        names
    }

    fn lenses_for_brand(&self, brand: &str) -> Vec<String> {
        let Some(b) = self.resolve_brand(brand) else { return Vec::new(); };
        let mut names: Vec<String> = self.lenses.iter()
            .filter(|l| l.brand_id == b.id)
            .map(|l| l.name.clone())
            .collect();
        names.sort_by(|a, b| a.to_ascii_lowercase().cmp(&b.to_ascii_lowercase()));
        names.dedup();
        names
    }

    pub fn resolve_brand(&self, raw: &str) -> Option<&Brand> {
        if raw.is_empty() || is_other(raw) { return None; }
        let key = brand_lookup_key(raw);
        self.brand_by_alias.get(&key).map(|&i| &self.brands[i])
    }

    pub fn resolve_camera(&self, brand: &str, model: &str) -> Option<&Camera> {
        if model.is_empty() || is_other(model) { return None; }
        let brand = self.resolve_brand(brand)?;
        let key = camera_match_key(&brand.id, model);
        self.camera_by_match.get(&key).map(|&i| &self.cameras[i])
    }

    pub fn resolve_lens(&self, brand: &str, model: &str, lens: &str) -> Option<&Lens> {
        if lens.is_empty() || is_other(lens) { return None; }
        let want = model_slug(lens);
        if want.is_empty() { return None; }
        let cam = self.resolve_camera(brand, model);
        let brand_id = cam.map(|c| c.brand_id.as_str())
            .or_else(|| self.resolve_brand(brand).map(|b| b.id.as_str()));

        self.lenses.iter().find(|l| {
            let name_hit = model_slug(&l.name) == want || l.aliases.iter().any(|a| model_slug(a) == want);
            if !name_hit { return false; }
            if let Some(cam) = cam {
                if l.camera_ids.iter().any(|id| id == &cam.id) { return true; }
                if !cam.fixed_lens && cam.mount_id.is_some() && l.mount_id == cam.mount_id { return true; }
            }
            if let Some(bid) = brand_id {
                return l.brand_id == bid;
            }
            false
        })
    }

    pub fn resolve(&self, brand: &str, model: &str, lens: &str) -> ResolvedSelection {
        let mut out = ResolvedSelection {
            brand: brand.trim().to_string(),
            model: model.trim().to_string(),
            lens: lens.trim().to_string(),
            used_other: is_other(brand) || is_other(model) || is_other(lens),
            ..Default::default()
        };
        if let Some(b) = self.resolve_brand(brand) {
            out.brand = b.name.clone();
            out.brand_id = Some(b.id.clone());
        } else if !brand.is_empty() && !is_other(brand) {
            out.used_other = true;
        }
        if let Some(c) = self.resolve_camera(&out.brand, model) {
            out.model = c.name.clone();
            out.camera_id = Some(c.id.clone());
            out.fixed_lens = c.fixed_lens;
            out.crop_factor = c.crop_factor;
            if let Some(mid) = c.mount_id.as_deref() {
                out.mount = self.mount_by_id.get(mid).map(|&i| self.mounts[i].name.clone());
            }
            if let Some(sid) = c.sensor_size_id.as_deref() {
                out.sensor_size = self.sensor_by_id.get(sid).map(|&i| self.sensor_sizes[i].name.clone());
            }
        } else if !model.is_empty() && !is_other(model) {
            out.used_other = true;
        }
        if let Some(l) = self.resolve_lens(&out.brand, &out.model, lens) {
            out.lens = l.name.clone();
            out.lens_id = Some(l.id.clone());
        } else if !lens.is_empty() && !is_other(lens) {
            // Lens names from video metadata are often FOV modes ("Wide") — keep them.
            out.lens = lens.trim().to_string();
        }
        out
    }

    pub fn compatible_cameras(&self, brand: &str, model: &str, limit: usize) -> Vec<CompatibleCamera> {
        let Some(cam) = self.resolve_camera(brand, model) else { return Vec::new(); };
        let Some(mount) = cam.mount_id.as_deref() else { return Vec::new(); };
        let Some(sensor) = cam.sensor_size_id.as_deref() else { return Vec::new(); };
        if cam.fixed_lens || mount == "fixed" { return Vec::new(); }

        let mut out = Vec::new();
        for other in &self.cameras {
            if other.id == cam.id { continue; }
            if other.mount_id.as_deref() != Some(mount) { continue; }
            if other.sensor_size_id.as_deref() != Some(sensor) { continue; }
            let brand_name = self.brand_by_id.get(&other.brand_id)
                .map(|&i| self.brands[i].name.clone())
                .unwrap_or_else(|| other.brand_id.clone());
            out.push(CompatibleCamera {
                brand: brand_name,
                model: other.name.clone(),
                mount: self.mount_by_id.get(mount).map(|&i| self.mounts[i].name.clone()),
                sensor_size: self.sensor_by_id.get(sensor).map(|&i| self.sensor_sizes[i].name.clone()),
                crop_factor: other.crop_factor,
            });
        }
        out.sort_by(|a, b| (a.brand.to_ascii_lowercase(), a.model.to_ascii_lowercase())
            .cmp(&(b.brand.to_ascii_lowercase(), b.model.to_ascii_lowercase())));
        if limit > 0 { out.truncate(limit); }
        out
    }

    /// Add any brand/model/lens strings from loaded Gyroflow profiles that the JSON missed.
    pub fn merge_from_profiles(&mut self, db: &LensProfileDatabase) {
        let mut added = 0usize;
        for profile in db.iter_unique_profiles() {
            if profile.camera_brand.is_empty() || profile.camera_model.is_empty() {
                continue;
            }
            if self.resolve_camera(&profile.camera_brand, &profile.camera_model).is_some() {
                if !profile.lens_model.is_empty() {
                    self.ensure_runtime_lens(profile);
                }
                continue;
            }
            let brand_id = if let Some(b) = self.resolve_brand(&profile.camera_brand) {
                b.id.clone()
            } else {
                let id = id_slug(&[&profile.camera_brand]);
                if !self.brands.iter().any(|b| b.id == id) {
                    self.brands.push(Brand {
                        id: id.clone(),
                        name: profile.camera_brand.clone(),
                        aliases: Vec::new(),
                    });
                }
                id
            };
            let cam_id = id_slug(&[&brand_id, &profile.camera_model]);
            self.cameras.push(Camera {
                id: cam_id,
                brand_id,
                name: profile.camera_model.clone(),
                aliases: Vec::new(),
                mount_id: None,
                sensor_size_id: None,
                crop_factor: profile.crop_factor,
                fixed_lens: true,
                sources: vec!["gyroflow".into()],
            });
            added += 1;
        }
        if added > 0 {
            log::info!("Camera database: added {added} cameras from loaded lens profiles");
        }
        self.rebuild_indexes();
        for profile in db.iter_unique_profiles() {
            self.ensure_runtime_lens(profile);
        }
        self.rebuild_indexes();
    }

    fn ensure_runtime_lens(&mut self, profile: &LensProfile) {
        if profile.lens_model.is_empty() { return; }
        if self.resolve_lens(&profile.camera_brand, &profile.camera_model, &profile.lens_model).is_some() {
            return;
        }
        let Some(cam) = self.resolve_camera(&profile.camera_brand, &profile.camera_model) else { return; };
        let lens = Lens {
            id: id_slug(&[&cam.brand_id, &profile.lens_model]),
            brand_id: cam.brand_id.clone(),
            name: profile.lens_model.clone(),
            aliases: Vec::new(),
            mount_id: cam.mount_id.clone(),
            camera_ids: vec![cam.id.clone()],
            focal_min_mm: profile.focal_length,
            focal_max_mm: profile.focal_length,
            aperture_min: None,
            kind: "unknown".into(),
            sources: vec!["gyroflow".into()],
        };
        self.lenses.push(lens);
    }

    pub fn profile_matches_setup(&self, profile: &LensProfile, brand: &str, model: &str, lens: &str) -> bool {
        if !brand.is_empty() && !is_other(brand) {
            let resolved = self.resolve_brand(brand).map(|b| b.name.as_str()).unwrap_or(brand);
            if !value_matches(&profile.camera_brand, resolved) && !value_matches(&profile.camera_brand, brand) {
                return false;
            }
        }
        if !model.is_empty() && !is_other(model) {
            let resolved = self.resolve_camera(brand, model).map(|c| c.name.as_str()).unwrap_or(model);
            if !camera_name_matches(&profile.camera_brand, &profile.camera_model, resolved)
                && !camera_name_matches(&profile.camera_brand, &profile.camera_model, model) {
                return false;
            }
        }
        if !lens.is_empty() && !is_other(lens) {
            if !value_matches(&profile.lens_model, lens) {
                return false;
            }
        }
        true
    }
}

impl LensProfileDatabase {
    pub fn iter_unique_profiles(&self) -> impl Iterator<Item = &LensProfile> {
        self.iter_profiles()
    }
}

fn is_other(s: &str) -> bool {
    s.eq_ignore_ascii_case(OTHER)
}

fn collapse_ws(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn brand_lookup_key(s: &str) -> String {
    collapse_ws(s).to_ascii_lowercase().replace(',', "")
}

fn model_slug(name: &str) -> String {
    let s = name.to_lowercase().replace('α', "a").replace('µ', "u").replace('μ', "u");
    let s: String = s.chars().filter(|c| c.is_ascii_alphanumeric()).collect();
    finish_model_slug(&s)
}

fn finish_model_slug(s: &str) -> String {
    let pairs = [
        ("viii", "8"), ("vii", "7"), ("iii", "3"), ("ii", "2"),
        ("ix", "9"), ("iv", "4"), ("vi", "6"),
    ];
    for (rom, dig) in pairs {
        if let Some(rest) = s.strip_suffix(rom) {
            return format!("{rest}{dig}");
        }
    }
    if s.ends_with('v') && s.len() > 1 {
        let bytes = s.as_bytes();
        if bytes[bytes.len() - 2].is_ascii_digit() {
            return format!("{}5", &s[..s.len() - 1]);
        }
    }
    s.to_string()
}

fn camera_match_slug(brand_id: &str, name: &str) -> String {
    let mut s = model_slug(name);
    if brand_id == "sony" {
        for prefix in ["sony", "alpha", "ilce", "ilme"] {
            if let Some(rest) = s.strip_prefix(prefix) {
                s = rest.to_string();
            }
        }
        if s.len() >= 2 && s.as_bytes()[s.len() - 2] == b'm' && s.as_bytes()[s.len() - 1].is_ascii_digit() {
            let mut t = s.as_bytes().to_vec();
            t.remove(t.len() - 2);
            s = String::from_utf8(t).unwrap_or(s);
        }
        if s.starts_with('6') || s.starts_with('7') {
            s = format!("a{s}");
        }
    } else if brand_id == "canon" {
        if let Some(rest) = s.strip_prefix("canon") { s = rest.to_string(); }
        if let Some(rest) = s.strip_prefix("eos") { s = rest.to_string(); }
    }
    s
}

fn camera_match_key(brand_id: &str, name: &str) -> String {
    format!("{}\0{}", brand_id, camera_match_slug(brand_id, name))
}

fn id_slug(parts: &[&str]) -> String {
    let raw = parts.join("_").to_ascii_lowercase().replace('α', "a");
    let mut out = String::new();
    let mut prev_us = false;
    for c in raw.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
            prev_us = false;
        } else if !prev_us {
            out.push('_');
            prev_us = true;
        }
    }
    let out = out.trim_matches('_').to_string();
    if out.is_empty() { "unknown".into() } else { out }
}

fn value_matches(profile: &str, selected: &str) -> bool {
    if profile.eq_ignore_ascii_case(selected) { return true; }
    let a = model_slug(profile);
    let b = model_slug(selected);
    !a.is_empty() && !b.is_empty() && (a == b || a.contains(&b) || b.contains(&a))
}

fn camera_name_matches(brand: &str, model: &str, selected: &str) -> bool {
    if value_matches(model, selected) { return true; }
    let brand_id = id_slug(&[brand]);
    camera_match_slug(&brand_id, model) == camera_match_slug(&brand_id, selected)
}

/// Iterator over unique (non-copy) profiles. Defined here so `camera_database`
/// does not need extra accessors on the profile map.
trait ProfileIter {
    fn iter_profiles(&self) -> Box<dyn Iterator<Item = &LensProfile> + '_>;
}

impl ProfileIter for LensProfileDatabase {
    fn iter_profiles(&self) -> Box<dyn Iterator<Item = &LensProfile> + '_> {
        Box::new(self.all_profiles().filter(|p| !p.is_copy && !p.camera_brand.is_empty()))
    }
}

impl LensProfileDatabase {
    /// Profiles as stored after `load_all` / `prepare_list_for_ui`.
    pub fn all_profiles(&self) -> impl Iterator<Item = &LensProfile> {
        self.raw_map().values()
    }

    pub fn search_by_setup<F>(&self, mut pred: F, favorites: &HashSet<String>, aspect_ratio: i32, aspect_ratio_swapped: i32) -> Vec<(String, String, String, bool, f64, i32, String)>
    where
        F: FnMut(&LensProfile) -> bool,
    {
        use std::cmp::Ordering;
        let mut filtered: Vec<(String, String, String, bool, f64, i32, String)> = Vec::new();
        for row in self.ui_list() {
            if let Some(profile) = self.get_by_id(&row.1) {
                if pred(profile) {
                    filtered.push(row.clone());
                }
            }
        }
        filtered.sort_by(|a, b| {
            let a_priority = a.1.ends_with(".gyroflow") || favorites.contains(&a.2);
            let b_priority = b.1.ends_with(".gyroflow") || favorites.contains(&b.2);
            if a_priority && !b_priority { return Ordering::Less; }
            if b_priority && !a_priority { return Ordering::Greater; }
            let a_priority2 = a.5 != 0 && aspect_ratio == a.5;
            let b_priority2 = b.5 != 0 && aspect_ratio == b.5;
            if a_priority2 && !b_priority2 { return Ordering::Less; }
            if b_priority2 && !a_priority2 { return Ordering::Greater; }
            let a_priority3 = a.5 != 0 && aspect_ratio_swapped == a.5;
            let b_priority3 = b.5 != 0 && aspect_ratio_swapped == b.5;
            if a_priority3 && !b_priority3 { return Ordering::Less; }
            if b_priority3 && !a_priority3 { return Ordering::Greater; }
            a.0.cmp(&b.0)
        });
        filtered.into_iter().take(200).collect()
    }
}

impl LensProfileDatabase {
    fn raw_map(&self) -> &HashMap<String, LensProfile> {
        self.profile_map()
    }
    fn ui_list(&self) -> &[(String, String, String, bool, f64, i32, String)] {
        self.list_for_ui_ref()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> CameraDatabase {
        CameraDatabase::from_json(r#"{
            "version": 1,
            "generated_at": "2026-01-01T00:00:00Z",
            "sources": {},
            "brands": [
                {"id": "sony", "name": "Sony", "aliases": ["SONY", "Sony Corporation"]},
                {"id": "gopro", "name": "GoPro", "aliases": ["gopro", "go pro"]}
            ],
            "mounts": [
                {"id": "sony_e", "name": "Sony E", "aliases": ["E"], "compat": [], "flange_focal_distance_mm": 18.0},
                {"id": "fixed", "name": "Fixed / built-in", "aliases": [], "compat": [], "flange_focal_distance_mm": null}
            ],
            "sensor_sizes": [
                {"id": "full_frame", "name": "Full frame", "width_mm": 36.0, "height_mm": 24.0, "crop_factor": 1.0, "aliases": ["FF"]},
                {"id": "aps_c", "name": "APS-C", "width_mm": 23.6, "height_mm": 15.6, "crop_factor": 1.5, "aliases": []}
            ],
            "cameras": [
                {"id": "sony_a7s_iii", "brand_id": "sony", "name": "Alpha 7S III", "aliases": ["A7S III", "a7sIII", "ILCE-7SM3"], "mount_id": "sony_e", "sensor_size_id": "full_frame", "crop_factor": 1.0, "fixed_lens": false, "sources": ["gyroflow", "lensfun"]},
                {"id": "sony_fx3", "brand_id": "sony", "name": "FX3", "aliases": ["ILME-FX3"], "mount_id": "sony_e", "sensor_size_id": "full_frame", "crop_factor": 1.0, "fixed_lens": false, "sources": ["gyroflow", "lensfun"]},
                {"id": "sony_fx30", "brand_id": "sony", "name": "FX30", "aliases": ["ILME-FX30"], "mount_id": "sony_e", "sensor_size_id": "aps_c", "crop_factor": 1.5, "fixed_lens": false, "sources": ["gyroflow", "lensfun"]},
                {"id": "gopro_hero11", "brand_id": "gopro", "name": "HERO11 Black", "aliases": ["Hero11 Black"], "mount_id": "fixed", "sensor_size_id": null, "crop_factor": 5.54, "fixed_lens": true, "sources": ["gyroflow"]}
            ],
            "lenses": [
                {"id": "sony_fe_24_70", "brand_id": "sony", "name": "FE 24-70mm F2.8 GM", "aliases": [], "mount_id": "sony_e", "camera_ids": [], "focal_min_mm": 24.0, "focal_max_mm": 70.0, "aperture_min": 2.8, "kind": "zoom", "sources": ["lensfun"]},
                {"id": "gopro_wide", "brand_id": "gopro", "name": "Wide", "aliases": [], "mount_id": "fixed", "camera_ids": ["gopro_hero11"], "focal_min_mm": null, "focal_max_mm": null, "aperture_min": null, "kind": "unknown", "sources": ["gyroflow"]}
            ]
        }"#).unwrap()
    }

    #[test]
    fn brand_aliases_resolve() {
        let db = fixture();
        assert_eq!(db.resolve_brand("sony").unwrap().name, "Sony");
        assert_eq!(db.resolve_brand("SONY").unwrap().name, "Sony");
        assert_eq!(db.resolve_brand("Sony Corporation").unwrap().name, "Sony");
        assert_eq!(db.resolve_brand("gopro").unwrap().name, "GoPro");
        assert!(db.resolve_brand("Other").is_none());
    }

    #[test]
    fn sony_body_codes_resolve_to_canonical_name() {
        let db = fixture();
        let cam = db.resolve_camera("Sony", "ILCE-7SM3").unwrap();
        assert_eq!(cam.name, "Alpha 7S III");
        assert_eq!(db.resolve_camera("sony", "a7sIII").unwrap().id, cam.id);
        assert_eq!(db.resolve_camera("Sony", "A7S III").unwrap().id, cam.id);
    }

    #[test]
    fn sony_full_frame_bodies_are_compatible() {
        let db = fixture();
        let compat = db.compatible_cameras("Sony", "FX3", 50);
        let models: Vec<_> = compat.iter().map(|c| c.model.as_str()).collect();
        assert!(models.contains(&"Alpha 7S III"), "{models:?}");
        assert!(!models.contains(&"FX30"), "APS-C FX30 must not be recommended for FX3: {models:?}");
        assert!(!models.contains(&"FX3"));
    }

    #[test]
    fn action_camera_has_no_interchangeable_compat() {
        let db = fixture();
        assert!(db.compatible_cameras("GoPro", "HERO11 Black", 50).is_empty());
        let lenses = db.lens_names("GoPro", "HERO11 Black");
        assert_eq!(lenses, vec!["Wide".to_string()]);
    }

    #[test]
    fn resolve_fills_mount_and_crop() {
        let db = fixture();
        let sel = db.resolve("sony", "ILME-FX3", "FE 24-70mm F2.8 GM");
        assert_eq!(sel.brand, "Sony");
        assert_eq!(sel.model, "FX3");
        assert_eq!(sel.lens, "FE 24-70mm F2.8 GM");
        assert_eq!(sel.mount.as_deref(), Some("Sony E"));
        assert_eq!(sel.sensor_size.as_deref(), Some("Full frame"));
        assert_eq!(sel.crop_factor, Some(1.0));
        assert!(!sel.fixed_lens);
        assert!(!sel.used_other);
    }

    #[test]
    fn bundled_catalog_sony_compat() {
        let db = CameraDatabase::bundled();
        assert!(db.cameras.len() > 100, "bundled catalog should include generated inventory");
        let a7s = db.resolve_camera("Sony", "ILCE-7SM3").expect("A7S III in catalog");
        let fx3 = db.resolve_camera("Sony", "FX3").expect("FX3 in catalog");
        assert_eq!(a7s.sensor_size_id.as_deref(), Some("full_frame"));
        assert_eq!(fx3.sensor_size_id.as_deref(), Some("full_frame"));
        let compat = db.compatible_cameras("Sony", "Alpha 7S III", 80);
        assert!(compat.iter().any(|c| c.model == "FX3"), "FX3 should be compatible with A7S III: {:?}", compat.iter().map(|c| &c.model).collect::<Vec<_>>());
        assert!(!compat.iter().any(|c| c.model == "FX30"), "FX30 is APS-C");
    }

    #[test]
    fn model_slug_roman_numerals() {
        assert_eq!(model_slug("A7S III"), model_slug("a7s3"));
        assert_eq!(camera_match_slug("sony", "ILCE-7SM3"), camera_match_slug("sony", "A7S III"));
        assert_eq!(camera_match_slug("sony", "ILME-FX3"), camera_match_slug("sony", "FX3"));
    }
}
