// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright © 2021-2022 Adrian <adrian.eddy at gmail>

use qmetaobject::qrc;

qrc!(pub rsrc,
    "/" {
        "src/ui/components/qmldir",
        "src/ui/menu/qmldir",
        "src/ui/qmldir",

        "resources/icon.png",
        "resources/logo_black.svg",
        "resources/logo_white.svg",
        "resources/icons/index.theme",
        "resources/icons/svg/axes.svg",
        "resources/icons/svg/bias.svg",
        "resources/icons/svg/bin.svg",
        "resources/icons/svg/chart.svg",
        "resources/icons/svg/checkmark.svg",
        "resources/icons/svg/chessboard.svg",
        "resources/icons/svg/chevron-down.svg",
        "resources/icons/svg/chevron-left.svg",
        "resources/icons/svg/chevron-right.svg",
        "resources/icons/svg/file-empty.svg",
        "resources/icons/svg/gyroflow.svg",
        "resources/icons/svg/info.svg",
        "resources/icons/svg/lens.svg",
        "resources/icons/svg/lock.svg",
        "resources/icons/svg/pause.svg",
        "resources/icons/svg/pencil.svg",
        "resources/icons/svg/play.svg",
        "resources/icons/svg/plus.svg",
        "resources/icons/svg/save.svg",
        "resources/icons/svg/search.svg",
        "resources/icons/svg/settings.svg",
        "resources/icons/svg/sound-mute.svg",
        "resources/icons/svg/sound.svg",
        "resources/icons/svg/spinner.svg",
        "resources/icons/svg/undo.svg",
        "resources/icons/svg/sync.svg",
        "resources/icons/svg/unlocked.svg",
        "resources/icons/svg/video.svg",
        "resources/icons/svg/fov-overview.svg",
        "resources/icons/svg/confirmed.svg",
        "resources/icons/svg/error.svg",
        "resources/icons/svg/warning.svg",
        "resources/icons/svg/question.svg",
        "resources/icons/svg/readout_time.svg",
        "resources/icons/svg/queue.svg",
        "resources/icons/svg/queue2.svg",
        "resources/icons/svg/folder.svg",
        "resources/icons/svg/close.svg",
        "resources/icons/svg/keyframe.svg",
        "resources/icons/svg/ease_in.svg",
        "resources/icons/svg/ease_out.svg",
        "resources/icons/svg/star.svg",
        "resources/icons/svg/star_empty.svg",
        "resources/icons/svg/stars5.svg",
        "resources/icons/svg/stars5_empty.svg",
        "resources/icons/svg/loop.svg",

        "src/core/gpu/compiled/stabilize.frag.qsb",
        "src/qt_gpu/compiled/texture.vert.qsb",
        "src/qt_gpu/compiled/undistort_opencv_fisheye.frag.qsb",
        "src/qt_gpu/compiled/undistort_opencv_fisheye_gopro_hyperview.frag.qsb",
        "src/qt_gpu/compiled/undistort_opencv_fisheye_gopro_superview.frag.qsb",
        "src/qt_gpu/compiled/undistort_opencv_standard_digital_stretch.frag.qsb",
        "src/qt_gpu/compiled/undistort_opencv_fisheye_digital_stretch.frag.qsb",
        "src/qt_gpu/compiled/undistort_opencv_standard.frag.qsb",
        "src/qt_gpu/compiled/undistort_poly3_digital_stretch.frag.qsb",
        "src/qt_gpu/compiled/undistort_poly3.frag.qsb",
        "src/qt_gpu/compiled/undistort_poly5_digital_stretch.frag.qsb",
        "src/qt_gpu/compiled/undistort_poly5.frag.qsb",
        "src/qt_gpu/compiled/undistort_ptlens_digital_stretch.frag.qsb",
        "src/qt_gpu/compiled/undistort_ptlens.frag.qsb",
        "src/qt_gpu/compiled/undistort_insta360_digital_stretch.frag.qsb",
        "src/qt_gpu/compiled/undistort_insta360.frag.qsb",

        "resources/translations/cs.qm",
        "resources/translations/da.qm",
        "resources/translations/de.qm",
        "resources/translations/el.qm",
        "resources/translations/es.qm",
        "resources/translations/fi.qm",
        "resources/translations/fr.qm",
        "resources/translations/gl.qm",
        "resources/translations/id.qm",
        "resources/translations/it.qm",
        "resources/translations/ja.qm",
        "resources/translations/ko.qm",
        "resources/translations/no.qm",
        "resources/translations/pl.qm",
        "resources/translations/pt_BR.qm",
        "resources/translations/pt.qm",
        "resources/translations/ru.qm",
        "resources/translations/sk.qm",
        "resources/translations/tr.qm",
        "resources/translations/uk.qm",
        "resources/translations/zh_CN.qm",
        "resources/translations/zh_TW.qm",
    }
);
