// SPDX-License-Identifier: GPL-3.0-or-later

use burn::tensor::{BoolStore, DType};
use burn_store::{ModuleAdapter, TensorSnapshot};
use std::rc::Rc;

/// Burnpack records generated by burn-onnx contain native boolean constants.
/// burn-store preserves the recorded dtype, but CubeCL cannot upload Native
/// bools. Adapt only their storage; do not downcast float or integer weights.
#[derive(Clone, Debug)]
pub(super) struct GpuBoolAdapter;

impl ModuleAdapter for GpuBoolAdapter {
    fn adapt(&self, snapshot: &TensorSnapshot) -> TensorSnapshot {
        let dtype = DType::Bool(BoolStore::U32);
        if !matches!(snapshot.dtype, DType::Bool(_)) || snapshot.dtype == dtype {
            return snapshot.clone();
        }
        let source = snapshot.clone_data_fn();
        let mut adapted = TensorSnapshot::from_closure(
            Rc::new(move || Ok(source()?.convert_dtype(dtype))),
            dtype,
            snapshot.shape.clone(),
            snapshot.path_stack.clone().unwrap_or_default(),
            snapshot.container_stack.clone().unwrap_or_default(),
            snapshot.tensor_id.unwrap_or_default(),
        );
        adapted.path_stack = snapshot.path_stack.clone();
        adapted.container_stack = snapshot.container_stack.clone();
        adapted.tensor_id = snapshot.tensor_id;
        adapted
    }

    fn clone_box(&self) -> Box<dyn ModuleAdapter> {
        Box::new(self.clone())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use burn::{module::ParamId, tensor::TensorData};

    fn snapshot(data: TensorData) -> TensorSnapshot {
        TensorSnapshot::from_data(
            data,
            vec!["model".into(), "mask".into()],
            vec!["Struct:Model".into()],
            ParamId::new(),
        )
    }

    #[test]
    fn boolean_import_preserves_values_shape_and_parameter_identity() {
        for storage in [BoolStore::Native, BoolStore::U8, BoolStore::U32] {
            let original = snapshot(
                TensorData::new(vec![true, false, false, true], [2, 2])
                    .convert_dtype(DType::Bool(storage)),
            );
            let adapted = GpuBoolAdapter.adapt(&original);
            assert_eq!(adapted.dtype, DType::Bool(BoolStore::U32));
            assert_eq!(adapted.shape, original.shape);
            assert_eq!(adapted.path_stack, original.path_stack);
            assert_eq!(adapted.container_stack, original.container_stack);
            assert_eq!(adapted.tensor_id, original.tensor_id);
            let data = adapted
                .to_data()
                .unwrap()
                .convert_dtype(DType::Bool(BoolStore::Native));
            assert_eq!(data.to_vec::<bool>().unwrap(), [true, false, false, true]);
            assert_eq!(original.dtype, DType::Bool(storage));
        }
    }

    #[test]
    fn non_boolean_import_preserves_float_and_integer_precision() {
        let values = [1.0f64 + f64::EPSILON, -1.0e200];
        let original = snapshot(TensorData::new(values.to_vec(), [2]));
        let adapted = GpuBoolAdapter.adapt(&original);
        assert_eq!(adapted.dtype, DType::F64);
        assert_eq!(adapted.to_data().unwrap().to_vec::<f64>().unwrap(), values);
        let values = [i64::MAX, i64::MIN];
        let original = snapshot(TensorData::new(values.to_vec(), [2]));
        let adapted = GpuBoolAdapter.adapt(&original);
        assert_eq!(adapted.dtype, DType::I64);
        assert_eq!(adapted.to_data().unwrap().to_vec::<i64>().unwrap(), values);
    }

    #[test]
    fn boolean_import_preserves_absent_metadata() {
        let mut original = snapshot(TensorData::new(vec![true], [1]));
        original.path_stack = None;
        original.container_stack = None;
        original.tensor_id = None;
        let adapted = GpuBoolAdapter.adapt(&original);
        assert!(adapted.path_stack.is_none());
        assert!(adapted.container_stack.is_none());
        assert!(adapted.tensor_id.is_none());
    }
}
